# Generated by Django 6.0.3 on 2026-03-05 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_fio', models.CharField(max_length=255, verbose_name='ФИО актера')),
            ],
            options={
                'verbose_name': 'Актер',
                'verbose_name_plural': 'Актеры',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название спектакля')),
                ('duration', models.IntegerField(verbose_name='Длительность (минуты)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL постера')),
            ],
            options={
                'verbose_name': 'Спекталь',
                'verbose_name_plural': 'Спектакли',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(verbose_name='Номер ряда')),
                ('seat_number', models.IntegerField(verbose_name='Номер места')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['row_number', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='TheaterHall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Основной зал', max_length=100, verbose_name='Название зала')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус билета',
                'verbose_name_plural': 'Статус билетов',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50, verbose_name='Тип действия')),
                ('description', models.TextField(verbose_name='Описание действия')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата действия')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayActor',
            fields=[
                ('play_actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_role_name', models.CharField(max_length=200, verbose_name='Название роли')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_plays', to='api.actor', verbose_name='Актер')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_actors', to='api.play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Роль актера в спектакле',
                'verbose_name_plural': 'Роли актеров в спектаклях',
                'unique_together': {('play', 'actor', 'actor_role_name')},
            },
        ),
        migrations.AddField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(related_name='plays', through='api.PlayActor', to='api.actor', verbose_name='Актеры'),
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('panorama_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image_url', models.CharField(max_length=500, verbose_name='URL изображения')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='api.seat', verbose_name='Место съемки')),
            ],
            options={
                'verbose_name': 'Панорама',
                'verbose_name_plural': 'Панорамы',
                'ordering': ['seat__row_number', 'seat__seat_number'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.play', verbose_name='Спектакль')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.theaterhall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['date', 'time'],
                'unique_together': {('hall', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('prediction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата прогноза')),
                ('predicted_tickets', models.IntegerField(verbose_name='Прогнозируемое количество билетов')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рекомендуемая цена')),
                ('confidence', models.FloatField(verbose_name='Уверенность прогноза (%)')),
                ('actual_tickets', models.IntegerField(blank=True, null=True, verbose_name='Фактически продано')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Прогноз ИИ',
                'verbose_name_plural': 'Прогнозы ИИ',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.theaterhall', verbose_name='Зал'),
        ),
        migrations.CreateModel(
            name='PanoramaLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа'), ('forward', 'Вперед'), ('back', 'Назад'), ('up', 'Вверх'), ('down', 'Вниз')], max_length=20, verbose_name='Направление')),
                ('hint', models.CharField(blank=True, max_length=100, verbose_name='Подсказка')),
                ('from_panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='api.panorama', verbose_name='Откуда')),
                ('to_panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='api.panorama', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Связь панорам',
                'verbose_name_plural': 'Связи панорам',
                'unique_together': {('from_panorama', 'to_panorama')},
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basket_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время добавления')),
                ('expires_at', models.DateTimeField(verbose_name='Бронь до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seat', verbose_name='Место')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'unique_together': {('session', 'seat')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'row_number', 'seat_number')},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата покупки/бронирования')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.seat', verbose_name='Место')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.session', verbose_name='Сеанс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='api.ticketstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'unique_together': {('session', 'seat')},
            },
        ),
    ]
