# Generated by Django 6.0.3 on 2026-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actor_play_seat_theaterhall_ticketstatus_actionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
