# Generated by Django 6.0.3 on 2026-03-24 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_genre_theaterhall_description_play_genres_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='api.sector', verbose_name='Сектор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата действия'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
