# Generated by Django 6.0.3 on 2026-03-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_panorama_sector_alter_actionlog_action_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='api.sector', verbose_name='Сектор'),
        ),
    ]
