# Generated by Django 6.0.3 on 2026-03-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seat_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panorama',
            name='sector',
        ),
    ]
