# Generated by Django 4.2.11 on 2026-03-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_panorama_sector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('hall', 'sector', 'row_number', 'seat_number')},
        ),
    ]
