# Generated by Django 4.2.11 on 2026-03-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ticket_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['sector', 'row_number', 'seat_number'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
