# Generated by Django 4.2.11 on 2026-04-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_seat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActor',
            fields=[
                ('session_actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_role_name', models.CharField(max_length=200, verbose_name='Название роли')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_actors', to='api.actor', verbose_name='Актер')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_actors', to='api.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Актер в сеансе',
                'verbose_name_plural': 'Актеры в сеансах',
                'unique_together': {('session', 'actor', 'actor_role_name')},
            },
        ),
        migrations.RemoveField(
            model_name='aiprediction',
            name='actual_tickets',
        ),
        migrations.RemoveField(
            model_name='aiprediction',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='aiprediction',
            name='predicted_price',
        ),
        migrations.RemoveField(
            model_name='play',
            name='actors',
        ),
        migrations.DeleteModel(
            name='PlayActor',
        ),
    ]
