# Generated by Django 4.2.11 on 2026-04-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sessionactor_remove_aiprediction_actual_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='genres',
        ),
        migrations.AddField(
            model_name='play',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='api.genre', verbose_name='Жанр'),
        ),
    ]
