# Generated by Django 4.2.11 on 2026-04-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panorama',
            name='image_url',
        ),
        migrations.AddField(
            model_name='panorama',
            name='image',
            field=models.ImageField(default='', upload_to='panoramas/'),
            preserve_default=False,
        ),
    ]
