# Generated by Django 4.2.11 on 2026-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_panorama_image_url_panorama_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='role',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
