# Generated by Django 4.2.11 on 2026-04-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
