# Generated by Django 4.2.11 on 2026-04-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_session_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='role',
        ),
    ]
