# Generated by Django 4.2.11 on 2026-04-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_session_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['session_id'], 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
    ]
