# Generated by Django 4.2.30 on 2026-05-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_session_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCoefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('morning', 'Утро (06:00-11:59)'), ('afternoon', 'День (12:00-17:59)'), ('evening', 'Вечер (18:00-21:59)'), ('night', 'Ночь (22:00-05:59)')], max_length=20, unique=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Коэффициент времени',
                'verbose_name_plural': 'Коэффициенты времени',
            },
        ),
        migrations.CreateModel(
            name='WeekdayCoefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], unique=True, verbose_name='День недели')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Коэффициент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Коэффициент дня недели',
                'verbose_name_plural': 'Коэффициенты дней недели',
                'ordering': ['weekday'],
            },
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['actor_id'], 'verbose_name': 'Актер', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['genre_id'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['play_id'], 'verbose_name': 'Спекталь', 'verbose_name_plural': 'Спектакли'},
        ),
        migrations.AlterModelOptions(
            name='sessionactor',
            options={'ordering': ['session_actor_id'], 'verbose_name': 'Актер в сеансе', 'verbose_name_plural': 'Актеры в сеансах'},
        ),
        migrations.RemoveField(
            model_name='sector',
            name='panorama_url',
        ),
        migrations.AddField(
            model_name='sector',
            name='price_coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Коэффициент цены сектора'),
        ),
        migrations.AddField(
            model_name='session',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рассчитанная цена сеанса'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('month', models.IntegerField(verbose_name='Месяц (1-12)')),
                ('day', models.IntegerField(verbose_name='День (1-31)')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
                'ordering': ['month', 'day'],
                'unique_together': {('month', 'day')},
            },
        ),
    ]
