# Generated by Django 4.2.30 on 2026-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price_at_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена на момент добавления'),
        ),
    ]
