# Generated by Django 4.2.30 on 2026-05-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_basket_price_at_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='baskets_data',
        ),
        migrations.AddField(
            model_name='payment',
            name='tickets_data',
            field=models.JSONField(default=list),
        ),
    ]
