# Generated by Django 4.2.30 on 2026-05-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ticket_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ручная цена (переопределяет расчётную)'),
        ),
    ]
