# Generated by Django 4.2.30 on 2026-05-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_session_custom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panorama',
            name='image',
        ),
        migrations.AddField(
            model_name='panorama',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL панорамы'),
        ),
    ]
