# Generated by Django 4.2.30 on 2026-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_panorama_image_panorama_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая цена'),
        ),
    ]
