# Generated by Django 4.2.30 on 2026-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_returnrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='id',
        ),
        migrations.RemoveField(
            model_name='timecoefficient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='weekdaycoefficient',
            name='id',
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timecoefficient',
            name='time_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekdaycoefficient',
            name='weekday_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('cancelled', 'Отменён'), ('refunded', 'Возвращён'), ('expired', 'Истёк')], default='pending', max_length=20),
        ),
    ]
